<a href="https://colab.research.google.com/github/RishabGowda/DeepLearning/blob/main/DLBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

List

In [14]:
list1=[1,5,4]
list2=[[1,2,3],[4,5,6]]

NumPY


In [21]:
import torch
import numpy as np
np1=np.random.rand(4)
np1
#np1.dtype

array([0.01925471, 0.30098998, 0.11459467, 0.9942036 ])

Tensor

In [20]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[-0.4278,  0.4137, -1.5416,  0.0900],
        [-0.3048, -0.8188, -0.6270,  0.7337],
        [-0.9721,  1.0533, -0.0450, -0.8754]])

In [16]:
tensor_3d=torch.randn(2,3,4)
tensor_3d

tensor([[[-0.6420,  0.1289, -0.8342, -0.3849],
         [ 0.5835, -0.7673,  0.8252, -0.1929],
         [ 1.8136, -0.5507, -0.4505,  1.5219]],

        [[ 0.2114,  1.4429, -0.0664,  0.0160],
         [-0.3648, -1.3064, -0.4783,  0.0966],
         [ 0.6056, -1.2609,  0.8352,  0.6879]]])

In [17]:
##create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([0.3346, 0.9150, 0.8231, 0.5524], dtype=torch.float64)

Tensor Operations


In [59]:
import torch
mytorch1=torch.arange(10)
mytorch1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#Reshape and View
mytorcchh=mytorch.reshape(2,5)
mytorcchh

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [54]:
#reshape if we dont know the number of items using -1
mytorch2=torch.arange(15)
mytorch2


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
mytorchh=mytorch2.reshape(3,-1)
mytorchh

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [60]:
#same as above but reverse (-1, 3)
mytorchh=mytorch2.reshape(-1,3)
mytorchh

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

View, similar to Reshape

In [61]:
mytorch3=torch.arange(10)
mytorch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
torcchhh=mytorch3.view(2,5)
torcchhh


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [64]:
#with reshape and view, they will update
mytorch4=torch.arange(10)
mytorch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
mytorch5=mytorch4.reshape(2,5)
mytorch5


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [67]:
mytorch4[1]=404
mytorch4

tensor([  0, 404,   2,   3,   4,   5,   6,   7,   8,   9])

In [68]:
mytorch5

tensor([[  0, 404,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

in this above if we made any changes in the original tensor with reshape and view, that changes will updated


In [69]:
#Slices
mytorch6=torch.arange(10)
mytorch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
mytorch6[3] #specific element through index

tensor(3)

In [74]:
#grab a slice
mytorch7=mytorch6.reshape(5, -1)
mytorch7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [79]:
mytorch7[:,1]

tensor([1, 3, 5, 7, 9])

In [82]:
#returb column
mytorch7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

**Basic Tensor MATH Operations**

In [83]:
import torch
import numpy as np


In [89]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
#addition
tensor_a + tensor_b



tensor([ 6,  8, 10, 12])

In [88]:
#addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [90]:
#subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [91]:
#Subtraction longhand
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [92]:
#multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [93]:
#multiplication longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [94]:
#Division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [101]:
#Division longhand
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [97]:
#modulus
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [98]:
#modulus longhand
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [99]:
#exponent
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [108]:
#reassignment
#tensor_a = tensor_a + tensor_b
#tensor_a
#OR
tensor_a.add_(tensor_b)
tensor_a

tensor([41, 50, 59, 68])